### PR TITLE
Columns in base classes with the meta flag 'abstract' are now included in the derived class.

### PR DESCRIPTION
**Pull request by xuru**
This PR enables having `Columns` in base classes as long as there is a `Meta` class and the flag `abstract` is set to `True`.

I've added test cases where I thought it was appropriate, but let me know if I missed anything.

I'll add documentation once you guys let me know if this is useful to you.

### CODE REVIEW

**Comment by xuru** [comment]
This will fix bug #72

**Comment by numberoverzero** [comment]
Thanks for the PR!  This is pretty ambitious, and taken together with #93 is a good start in on closing #72.  I think any inheritance impl has a good chance of creating subtle bugs, which is partially why it's remained an open item for so long[0].  That's just to say I expect this to have a bit more bake time than the average PR[1].

We don't need an answer to all of the following in this PR, but I want to ensure this implementation will let us solve them:

* A `GlobalSecondaryIndex` on a derived model should be able to refer to a `Column` on the abstract parent
* We should be able to safely remove references to `self.model` from `Column`, and find a workaround for rendering them (see `Column.__repr__`, which is the only non-internal use)
* Support multiple abstract bases, so they can be used as mixins.  For example, `class User(UUIDHashKey, StringRangeKey)` or `class Manager(Employee, WithEmail)`
* What happens to columns and indexes when an abstract model inherits from a concrete?  For example, where `Cx` is a concrete model and `Ax` is an abstract model: `BaseModel -> A0 -> C1 -> C2 -> A3 -> A4`
* What happens when there's a name collision on an inherited model?  For example, `C1` defines `id = Column(Integer, hash_key=True)` and `C2` defines `id = Column(Integer, hash_key=True)`?
* Is there any limitation on inheriting columns tagged as the `hash_key` or `range_key`?
* How will these work with queries and scans, which determine the model from the passed index?  (See `bloop/engine.py::Engine.query` for the index -> model resolution)
* Do we need to think about how column types bind to the type engine?  I think duplicates are ignored, but we should verify that.
---

[0] It's been almost 2 years since I first started thinking about inheritance; although #72 is under a year old, #26 predates it by almost a year.  I've suspected that any solution will use a very thin proxy class, similar to the class `bloop/conditions.py::Proxy` which is created whenever a column path is used (eg. `User.metadata["emails"][0].begins_with(...)`) to provide a pseudo-copy-on-write behavior.  I'm not positive it's required, but it may be worth considering when we look at the above questions.

[1] For example, exposing a `default=` option on the `Column` class should be pretty easy, but ran into complexity when considering the return value of a query against a partial projection, or explicitly deleted values.  See https://github.com/numberoverzero/bloop/pull/90#issuecomment-327749836 for more details.

**Comment by xuru** [comment]
Thanks for the timely response!  Like I said in #93, I'm coming over from [flywheel](https://github.com/stevearc/flywheel), and have lots of code that does this already.  However, you make a lot of great points.  Let me take a stab at a few of them:

Here is an idea (and I kind of already do this [here](https://github.com/xuru/bloop/blob/feature/abstract_base_columns/bloop/models.py#L107):  What if we consider all abstract classes as blueprints in constructing the concrete class?  So, we go through all the base classes that are abstract, determine the columns, and construct those in the concrete class.  We don't need to refere to the base class at all.

> A GlobalSecondaryIndex on a derived model should be able to refer to a Column on the abstract parent

As all columns will be of the concrete class, this shouldn't need to change.

>We should be able to safely remove references to self.model from Column, and find a workaround for rendering them (see Column.__repr__, which is the only non-internal use)

As all columns will be of the concrete class, this shouldn't need to change.

> Support multiple abstract bases, so they can be used as mixins. For example, class User(UUIDHashKey, StringRangeKey) or class Manager(Employee, WithEmail)

Again, this shouldn't be a problem as long as they are derived from BaseModel, and set `abstract = True`.

> What happens to columns and indexes when an abstract model inherits from a concrete?

That should not be allowed.  We can add in a check for any concrete classes in the list of bases, and throw an exception.

> What happens when there's a name collision on an inherited model?

As it's just a blueprint on creating the class, it's determined by MRO of the class.  The last one wins.

> Is there any limitation on inheriting columns tagged as the `hash_key` or `range_key`?

Again, we can add a check for multiple hash or range keys, and throw an exception.

> How will these work with queries and scans, which determine the model from the passed index? (See bloop/engine.py::Engine.query for the index -> model resolution)

As the index is recreated on the concrete class, this wouldn't be a problem.

> Do we need to think about how column types bind to the type engine? I think duplicates are ignored, but we should verify that.

I believe we are ok here as well, because duplicates are weeded out (OrderedDict is use for attributes).

Let me change a few things around for the points above and see what you think.

**Comment by xuru** [comment]
Another thought, is doing what flywheel does: https://github.com/stevearc/flywheel/blob/master/flywheel/model_meta.py#L206

By using `inspect` to get all the fields, and setting the `self.model` on the fields.  The pros for this method that it will look correct when inspecting it in a debugger...

**Comment by numberoverzero** [comment]
A minimal example of the desired behavior in bloop could be helpful to nail down the moving parts.  Could you write up an example with 2 or 3 classes showing the inheritance you're looking for?

> By using inspect to get all the fields, and setting the self.model on the fields. The pros for this method that it will look correct when inspecting it in a debugger...

We already set model on the column on line 170: https://github.com/numberoverzero/bloop/blob/933fa9f102c5f53b9c5a1979d99bb73c18a8aef2/bloop/models.py#L136-L171

**Comment by xuru** [comment]
Ok, I think maybe you'll like this...   I did a more deep dive into how it all works and came up with a better solution.

Here is the example code that works:
https://gist.github.com/xuru/aa617d2de8fe3facea9d3a5d700b5d29

**Comment by numberoverzero** [comment]
That gist is exactly what I was hoping for, thank you!

1. Why does `ExternalUser` derive from `MyBaseModel` and `BaseModel`?
2. What about subclassing `User`?  I don't want to make another class that shares the same attributes just because `User` is concrete; I still want my `isinstance(obj, User` checks to succeed even though it's `SomeUserSubclass` that adds one field.
3. Can you add a line after the scan that shows `engine.query(SomeUserSubclass.by_email, ...)` which covers using the GSI of a base class in the derived class?  I think this is the primary place the blueprint pattern is necessary, so that the derived class's index points at the right model.

**Comment by xuru** [comment]
> Why does ExternalUser derive from MyBaseModel and BaseModel?

I wanted to test MRO.  Just in case there was some weirdness on when BaseModel it hit first.  However, it's illegal to list BaseModel first in the list in python3, so we don't have to really worry about it.

> What about subclassing User? I don't want to make another class that shares the same attributes just because User is concrete; I still want my isinstance(obj, User checks to succeed even though it's SomeUserSubclass that adds one field.

So this is where I had to make a decision between design and complexity.  It's *much* easier to ensure that all base classes are abstract, then it is to re-write most of how declare and binding works.  I think this is a good compromise that Flywheel and others have made as well.  If the example gist was real code, I would probably make a `BaseUser`, and derive both `User` and `ExternalUser` from that `BaseUser`.

> Can you add a line after the scan that shows engine.query(SomeUserSubclass.by_email, ...) which covers using the GSI of a base class in the derived class? I think this is the primary place the blueprint pattern is necessary, so that the derived class's index points at the right model.

Absolutely.  I'll get these into unit tests soon as well.

**Comment by xuru** [comment]
Ok, updated my gist:  https://gist.github.com/xuru/aa617d2de8fe3facea9d3a5d700b5d29

**Comment by numberoverzero** [comment]
Added some comments.  Thanks for writing up the sample, it's much easier to discuss with concrete code to point at.

**Comment by xuru** [comment]
@numberoverzero Couple of things with my latest commit:

1) I haven't squashed my branch so you can see my progression
2) I had to replace the TypeEngine to keep track of bound types by name instead of instance.  I was having all kinds of issues with model attributes having the wrong type based on previous tests.

**Comment by numberoverzero** [comment]
I've got a slack and gitter set up if it's easier to coordinate.  Otherwise I'm fine continuing to use this PR.

Looking over the `TypeEngine` stuff I think that it might be time to refactor and simplify.  It's designed to support baking config into load/dump functions, but in almost every case a Bloop type is only going to use the actual `Type._dump`, `Type._load` functions.  I'm not opposed to replacing or removing it to simplify things, but I'd like to do that in its own PR.

As for field ordering, we could potentially drop `declare.Field` (with the `TypeEngine` refactor, this removes `declare` entirely) if bloop adopts the features from [PEP 487](https://www.python.org/dev/peps/pep-0487/): `__init_subclass__` and `__set_name__`.  Since that moves the minimum python from 3.5 to 3.6, that would require a major version change.

**Comment by xuru** [comment]
> I've got a slack and gitter set up if it's easier to coordinate. Otherwise I'm fine continuing to use this PR.

I was going to suggest this, as it will make asking question much easier.  What is the slack url?

I agree that, although it's a very interesting and well done package, delcare isn't as flexible as I think we need.

**Comment by numberoverzero** [comment]
I've pushed the [refactor-type-engine branch](/github/numberoverzero/bloop/refactor-type-engine) which removes declare as a dependency.  You may want to see if it's easier to build off of that.  It requires python 3.6.

**Comment by xuru** [comment]
> bloop-dev.slack.com

I made my email public if you want to invite me.  Thanks again!

> I've pushed the refactor-type-engine branch which removes declare as a dependency. You may want to see if it's easier to build off of that. It requires python 3.6.

I'll have a look when I get a chance.

**Comment by numberoverzero** [comment]
Closing this since we've got inheritance working in the dev-2.0 branch.

**Pull request closed without merging**
