### PR TITLE
Derive some meta attributes.

### PR DESCRIPTION
**Pull request by xuru**
Ensure that read and write units are passed down to derived classes, as well as streams (although I'm not sure about this logic as I don't use streams).

### CODE REVIEW

**Comment by xuru** [comment]
Hmm.. not sure what it's complaining about, because it certainly hits those lines of code...

**Comment by xuru** [comment]
Ok, I set the list of attributes that will carry over to derived Meta classes to `read_units`, `write_units` and a new `table_prefix`.  The `table_prefix` prefixes the table name with it's value.  As this will be carried down to it's derived classes, you can have a base class defined as something like:

```
class MyBaseClass(BaseModel):
    class Meta:
        abstract = True
        table_prefix = get_config().ENVIRONMENT  # Something like dev or staging
    pass

class MyClass(MyBaseClass):  # tables name will be something like dev-MyClass or staging-MyClass
    pass

```

**Comment by numberoverzero** [comment]
As with #92, thanks for taking on this work!  Any inheritance impl will need to make copying `Meta` attributes easy, so this is a great step towards a solution.

I'm leaving the more general how-does-inheritance-work discussion for #72 and #92, so comments here are just focused on the `Meta` class inheritance.

* I like the idea of `table_prefix` as a user, but it's a little too specific for bloop to care about; why then not `table_suffix` or `table_pattern`?  Instead of whitelisting property names, what about just copying everything down from the base?  That way users' custom values always work (the alternative is they have to hack onto the whitelist themselves).
* What are the rules when a base class is bound (possibly injecting a stream arn) and then a class is derived from that?  Does the derived class take the bound stream arn?
* The same question applies to table read_units and write_units; in an upcoming change (the next few hours) the default behavior will change (see #88) such that omitting them will no longer default to 1/1, but will take their values from the existing DescribeTable.  In that case, deriving a class after binding the base class will grab the bound read/write units, and not the base class's intent, which was "get these from Dynamo".  Can we preserve that information without polluting the original Meta object or leaking memory by holding on to large custom meta properties?

**Comment by xuru** [comment]
Thanks for the thoughtful response!  

A little background first...  I'm a refugee from the [flywheel](https://github.com/stevearc/flywheel) project, and porting to this library seemed the easiest transition. But there are features that are missing, that I would like to implement.

So, my original intent with this was to add a prefix to table names.  In the [flywheel](https://github.com/stevearc/flywheel) package, you can pass in the "namespace" into the engine on creation.  I use this to prefix all tables with the environment they are deployed too.  For example, develop_user, staging_user, prod_user tables.

So with that in mind, I poked around the table creation code, and noticed that there were a lot of references to the obj.Meta.table_name without any translation methods under the hood.  So I figured the only place to make that prefix was in the metaclass for model creation.

Perhaps there is a better way to do this.  What about having an internal metadata class that holds the information gleaned from the model.Meta classes?  That way, we can have computed properties on that metadata, etc...

**Comment by numberoverzero** [comment]
For prefixing table names, I'd recommend connecting to the [`before_create_table`](http://bloop.readthedocs.io/en/latest/api/public.html#bloop.signals.before_create_table) signal.  The example suffixes table names with a nonce, but that's an easy transition:


```python
def table_prefix_for(model):
    """
    Maybe this inspects the model name, or model columns to select
    the appropriate namespace.  Or, it always returns the same fixed value.
    """
    return "my-table-"

@before_create_table.connect
def apply_table_prefix(_, model, **__):
    prefix = table_prefix_for(model)    
    model.Meta.table_name = prefix + model.Meta.table_name
```

The integ tests use a [configurable nonce suffix](https://github.com/numberoverzero/bloop/blob/933fa9f102c5f53b9c5a1979d99bb73c18a8aef2/tests/integ/conftest.py#L19-L36) so that simultaneous runs don't interact, but still offer a way to set the nonce explicitly.

**Comment by xuru** [comment]
We can probably close this one then, unless there is something that you want to derive.  I'll add a pattern for people wanting to do environment sharded tables as well.

**Comment by numberoverzero** [comment]
Closing for now.  I suspect we'll revisit the Meta class as we get further into abstract inheritance and mixins, but I'd like to tackle that when column/index inheritance is working.

**Pull request closed without merging**
